version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/test-app # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:14.0 # ...with this image as the primary container; this is where all `steps` will run
    
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - add_ssh_keys:
            fingerprints:
                - "2c:11:9c:9a:2f:da:2f:71:52:16:d6:67:8e:e0:f3:ee"
  - deploy:
        name: deployment
        command: ssh -o "StrictHostKeyChecking no" root@68.183.90.186 "cd ~ && rm -rf test-app && git clone https://github.com/Sagar2177/Node-App-Deployment-with-Circle-CI.git test-app && cd test-app && sh post_deployment.sh "