
version: 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/test-app
    steps: # a collection of executable commands
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-dependencies
          command: npm install
          paths:
            - ./node_modules
      - run:
          name: install-dependencies
          command: node test.js
          
      